# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
  working_directory: ~/code/repo
  docker:
    - image: circleci/node

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Installing
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/code/repo
          paths:
            - node_modules

  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/code/repo
      - run:
          name: Linting
          command: yarn js:lint

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/code/repo
      - run:
          name: Testing
          command: yarn test:coverage:ci

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/code/repo
      - run:
          name: Building JS
          command: yarn js:build:prod
      - persist_to_workspace:
          root: ~/code/repo
          paths:
            - node_modules
            - build

  publish:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/code/repo
      - run:
          name: Publish NPM package
          command: yarn semantic-release || true

workflows:
  version: 2
  install-lint-test-build-release:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - lint
      - build:
          requires:
            - test
      - publish:
          filters:
            branches:
              only: master
          requires:
            - build

